### PR TITLE
Allow passing deserialized object as source.

### PR DESCRIPTION
**Pull request by btimby**
Looks like the underlying asyncapi `parse()` function allows for this.

https://github.com/asyncapi/parser-js/blob/master/API.md#asyncapiparserparseasyncapiyamlorjson-options--promiseasyncapidocument

`parse()` calls this:
https://github.com/asyncapi/parser-js/blob/aba3ed25a58e1eb36b77d5e7dd724202ca737f64/lib/utils.js#L108

I already import my schema from a .json file in my project. I would prefer to avoid loading from disk twice.

### CODE REVIEW

**Comment by WaleedAshraf** [comment]
@btimby Hi,
Can you also add tests for this, and update the docs, please. 👍

**Comment by btimby** [comment]
Sure, I modified `README.md` are there other docs that need attention?

**Review by WaleedAshraf — APPROVED** [review]

**Comment by WaleedAshraf** [comment]
I'll release a new version in a couple of days. Thanks. 👍

**Comment by btimby** [comment]
@WaleedAshraf no problem, thank you sir!

**Pull request merged**
